apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # port exposé dans le cluster
      targetPort: 8000  # port sur lequel l'application écoute dans le pod